#!/bin/sh

# Install the AOA Twenty Twenty Twenty alert for MacOS. Note that
# `aoa-ttt-install` is idempotent.
#
# Usage: `aoa-ttt-install`

set -u

if [ $# -ne 0 ]
   then echo "Usage: $0"
fi

crontab_line="*/20 * * * * osascript -e 'display notification \"Look at something 20 feet away for 20 seconds\" with title \"AOA-TTT: Rest your eyes 👀\"'"

(crontab -l 2&>/dev/null; echo "$crontab_line") | crontab -
